name: website

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  website:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3

      - run: corepack enable
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      # Install the top-level packages.
      - run: yarn
      - run: yarn playwright install chromium-headless-shell --with-deps

      # Install the website packages, then test.
      - name: Test assets/test folder
        run: 'yarn dev:static && yarn dev:static --selector data-qa-id'

      - name: Test website folder
        run: yarn --cwd website && yarn test:ci

      # Build the website.
      - name: Build
        working-directory: ./website
        run: yarn build
        env:
          VITE_BASE_PATH: /text-to-playwright

      - name: Prepare publish
        working-directory: ./
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          mkdir -p ./output
          cp -r website/dist/* output

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          # Publish only with the latest commit.
          # Source: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-force-orphan-force_orphan.
          force_orphan: true
